// Code generated by MockGen. DO NOT EDIT.
// Source: ./apis.go

// Package mock_traffic_service is a generated GoMock package.
package mock_traffic_service

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	traffic_service "where-do-i-sit/internal/app"
)

// MockTrafficServiceAPI is a mock of TrafficServiceAPI interface.
type MockTrafficServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTrafficServiceAPIMockRecorder
}

// MockTrafficServiceAPIMockRecorder is the mock recorder for MockTrafficServiceAPI.
type MockTrafficServiceAPIMockRecorder struct {
	mock *MockTrafficServiceAPI
}

// NewMockTrafficServiceAPI creates a new mock instance.
func NewMockTrafficServiceAPI(ctrl *gomock.Controller) *MockTrafficServiceAPI {
	mock := &MockTrafficServiceAPI{ctrl: ctrl}
	mock.recorder = &MockTrafficServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrafficServiceAPI) EXPECT() *MockTrafficServiceAPIMockRecorder {
	return m.recorder
}

// GetStationByName mocks base method.
func (m *MockTrafficServiceAPI) GetStationByName(arg0 string) (traffic_service.Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationByName", arg0)
	ret0, _ := ret[0].(traffic_service.Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationByName indicates an expected call of GetStationByName.
func (mr *MockTrafficServiceAPIMockRecorder) GetStationByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationByName", reflect.TypeOf((*MockTrafficServiceAPI)(nil).GetStationByName), arg0)
}

// GetStationList mocks base method.
func (m *MockTrafficServiceAPI) GetStationList() ([]traffic_service.Station, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationList")
	ret0, _ := ret[0].([]traffic_service.Station)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationList indicates an expected call of GetStationList.
func (mr *MockTrafficServiceAPIMockRecorder) GetStationList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationList", reflect.TypeOf((*MockTrafficServiceAPI)(nil).GetStationList))
}
